// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgsezxkukfcfwnsgitnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nc2V6eGt1a2ZjZnduc2dpdG5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0Mzg5NzQsImV4cCI6MjA2MjAxNDk3NH0.99QaGD__NVROucWt5vwr3bbp96XGevoJ7LtdohmK2TI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});